// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://immoomagkwqjexnobymk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbW9vbWFna3dxamV4bm9ieW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjczNTAzMjcsImV4cCI6MjA0MjkyNjMyN30.QiIZj2EIlGybT4E2P0hNCtTagabsAwiTAH5VVFv7cuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);